### ISSUE TITLE
Problem with weather icons

### ISSUE THREAD

**Issue by blackbart420** [kamek-pf/polybar-forecast#2]
Hello again @kamek-pf 

Sorry to bother you but I now have some troubles with the weather icons font.
I installed the font package but it seems the module isn't using the font.

You'll see your weather module on the bottom right of the screenshot 

![screeshot](https://user-images.githubusercontent.com/15202659/52421995-7c2a1e80-2af5-11e9-9439-dd7c6c82169d.png)

Do you know how I could fix this ?

**Comment by kamek-pf** [comment]
Hey ;o

Pretty sure this is due to how Polybar chooses which font to apply when rendering something.
If I remember correctly, it's looking at all the fonts you defined in your Polybar config (in order) and stops as soon as one of them is able to render the glyphs.

In my own config, this is what I have :
```
font-0 = NotoSans-Regular:size=16;-1
font-1 = MaterialIcons:size=21;2
font-2 = FiraCode:size=16
font-3 = Weather Icons:size=18;1
font-4 = FontAwesome:size=16
```

You should try moving `Weather Icons` a few lines up, before the other icon fonts and see what works for you.

**Comment by blackbart420** [comment]
Hello @kamek-pf 
Thank you very much for your answer !

I did not define the weather font in my polybar config.
Now I added this line to my bottom bar config : 

font-9 = Weather Icons:size=12;1

and set this in your module/weather polybar config : 
label-font = 10

And now it works fine. Thanks for your time, that's a great module :)

**Comment by gu-maia** [comment]
Solved for me too, thanks!

**Comment by blurm** [comment]
Mine conflicts with font awesome.
If I put weather icon above font awesome, some of the font awesome's icon will be replaced.
I have to manually set the label-font.

**Comment by betaWeb** [comment]
> Mine conflicts with font awesome.
> If I put weather icon above font awesome, some of the font awesome's icon will be replaced.
> I have to manually set the label-font.

Same problem here !
